### ISSUE TITLE
train_scripts.py UnboundLocalError when validation loader = False

### ISSUE THREAD

**Issue by TibbersHao** [phzwart/dlsia#2]
Traceback:
File "/usr/local/lib/python3.9/site-packages/dlsia/core/train_scripts.py", line 237, in train_segmentation
    best_score = val_loss
UnboundLocalError: local variable 'val_loss' referenced before assignment

Suggest Solution: `best_score = loss`

**Comment by ericroberts89** [comment]
You suggestion has been implemented. Tested and works on Dev's end.
